<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
        DB::table('permissions')->truncate();

        $permissions = [

            [
                'id' => 1,
                'display_name' => 'ইউজার তৈরী করা',
                'name' => 'can-create-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'display_name' => 'ইউজার আপডেট করা',
                'name' => 'can-edit-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'display_name' => 'ইউজার ডিলিট করা',
                'name' => 'can-delete-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'display_name' => 'ইউজার দেখা',
                'name' => 'can-view-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'display_name' => 'ইউজার ডিটেইলস দেখা',
                'name' => 'can-view-details-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'display_name' => 'রোল তৈরী করা',
                'name' => 'can-create-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'display_name' => 'রোল আপডেট করা',
                'name' => 'can-edit-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'display_name' => 'রোল ডিলিট করা',
                'name' => 'can-delete-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'display_name' => 'রোল দেখা',
                'name' => 'can-view-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'display_name' => 'রোল ডিটেইলস দেখা',
                'name' => 'can-view-details-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'display_name' => 'পারমিশন তৈরী করা',
                'name' => 'can-create-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'display_name' => 'পারমিশন আপডেট করা',
                'name' => 'can-edit-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'display_name' => 'পারমিশন ডিলিট করা',
                'name' => 'can-delete-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'display_name' => 'পারমিশন দেখা',
                'name' => 'can-view-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            // [
            //     'id' => 15,
            //     'display_name' => 'কোম্পানি তৈরী করা',
            //     'name' => 'can-create-company',
            //     'guard_name' => 'web',
            //     'group_name' => 'Company Management',
            //     'is_active' => true,
            // ],
            [
                'id' => 16,
                'display_name' => 'স্টুডেন্ট দেখা',
                'name' => 'can-view-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'display_name' => 'স্টুডেন্ট তৈরী করা',
                'name' => 'can-create-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'display_name' => 'স্টুডেন্ট আপডেট করা',
                'name' => 'can-edit-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'display_name' => 'স্টুডেন্ট ডিলিট করা',
                'name' => 'can-delete-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'display_name' => 'স্টুডেন্ট ডিটেইলস দেখা',
                'name' => 'can-view-details-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'display_name' => 'ডিপার্টমেন্ট দেখা',
                'name' => 'can-view-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'display_name' => 'ডিপার্টমেন্ট তৈরী করা',
                'name' => 'can-create-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'display_name' => 'ডিপার্টমেন্ট আপডেট করা',
                'name' => 'can-edit-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'display_name' => 'ডিপার্টমেন্ট ডিলিট করা',
                'name' => 'can-delete-department',
                'guard_name' => 'web',
                'group_name' => 'Department Management',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'display_name' => 'হল দেখা',
                'name' => 'can-view-hall',
                'guard_name' => 'web',
                'group_name' => 'Hall Management',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'display_name' => 'হল তৈরী করা',
                'name' => 'can-create-hall',
                'guard_name' => 'web',
                'group_name' => 'Hall Management',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'display_name' => 'হল আপডেট করা',
                'name' => 'can-edit-hall',
                'guard_name' => 'web',
                'group_name' => 'Hall Management',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'display_name' => 'হল ডিলিট করা',
                'name' => 'can-delete-hall',
                'guard_name' => 'web',
                'group_name' => 'Hall Management',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'display_name' => 'রুম দেখা',
                'name' => 'can-view-room',
                'guard_name' => 'web',
                'group_name' => 'Room Management',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'display_name' => 'রুম তৈরী করা',
                'name' => 'can-create-room',
                'guard_name' => 'web',
                'group_name' => 'Room Management',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'display_name' => 'রুম আপডেট করা',
                'name' => 'can-edit-room',
                'guard_name' => 'web',
                'group_name' => 'Room Management',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'display_name' => 'রুম ডিলিট করা',
                'name' => 'can-delete-room',
                'guard_name' => 'web',
                'group_name' => 'Room Management',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'display_name' => 'রুমের ডিটেইলস দেখা',
                'name' => 'can-view-details-room',
                'guard_name' => 'web',
                'group_name' => 'Room Management',
                'is_active' => true,
            ],

            //Hall Attachment
            [
                'id' => 34,
                'display_name' => 'হল এটাচমেন্ট দেখা',
                'name' => 'can-view-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'display_name' => 'হল এটাচমেন্ট তৈরী করা',
                'name' => 'can-create-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            [
                'id' => 36,
                'display_name' => 'হল এটাচমেন্ট আপডেট করা',
                'name' => 'can-edit-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            [
                'id' => 37,
                'display_name' => 'হল এটাচমেন্ট ডিলিট করা',
                'name' => 'can-delete-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            [
                'id' => 38,
                'display_name' => 'হল এটাচমেন্ট ডিটেইলস দেখা',
                'name' => 'can-view-details-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            //Hall Allotment
            [
                'id' => 39,
                'display_name' => 'হল বরাদ্দ দেখা',
                'name' => 'can-view-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 40,
                'display_name' => 'হল বরাদ্দ তৈরী দেখা',
                'name' => 'can-create-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'display_name' => 'হল বরাদ্দ আপডেট দেখা',
                'name' => 'can-edit-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'display_name' => 'হল বরাদ্দ ডিলিট দেখা',
                'name' => 'can-delete-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'display_name' => 'হল বরাদ্দ ডিটেইলস দেখা',
                'name' => 'can-view-details-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'display_name' => 'রুম টাইপ দেখা',
                'name' => 'can-view-room-type',
                'guard_name' => 'web',
                'group_name' => 'Room Type Management',
                'is_active' => true,
            ],
            [
                'id' => 45,
                'display_name' => 'রুম টাইপ তৈরী করা',
                'name' => 'can-create-room-type',
                'guard_name' => 'web',
                'group_name' => 'Room Type Management',
                'is_active' => true,
            ],
            [
                'id' => 46,
                'display_name' => 'রুম টাইপ আপডেট করা',
                'name' => 'can-edit-room-type',
                'guard_name' => 'web',
                'group_name' => 'Room Type Management',
                'is_active' => true,
            ],
            [
                'id' => 47,
                'display_name' => 'রুম টাইপ ডিলিট করা',
                'name' => 'can-delete-room-type',
                'guard_name' => 'web',
                'group_name' => 'Room Type Management',
                'is_active' => true,
            ],
            [
                'id' => 48,
                'display_name' => 'রুম টাইপ ডিটেইলস দেখা',
                'name' => 'can-view-details-room-type',
                'guard_name' => 'web',
                'group_name' => 'Room Type Management',
                'is_active' => true,
            ],
            // Student Block
            [
                'id' => 49,
                'display_name' => 'ব্লক করা স্টুডেন্ট দেখা',
                'name' => 'can-view-block-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 50,
                'display_name' => 'ব্লক রিমুভ করা',
                'name' => 'can-delete-block-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            [
                'id' => 51,
                'display_name' => 'স্টুডেন্ট আনব্লক করা',
                'name' => 'can-unblock-student',
                'guard_name' => 'web',
                'group_name' => 'Student Management',
                'is_active' => true,
            ],
            // Hall Allotment Cancellation
            [
                'id' => 52,
                'display_name' => 'হল বরাদ্দ বাতিল করা',
                'name' => 'can-cancel-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 53,
                'display_name' => 'হল বরাদ্দ বাতিল অনুরোধ করা',
                'name' => 'can-request-cancel-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            [
                'id' => 54,
                'display_name' => 'হল বরাদ্দ বাতিল অনুমোদন করা',
                'name' => 'can-approve-cancel-hall-allotment',
                'guard_name' => 'web',
                'group_name' => 'Hall Allotment Management',
                'is_active' => true,
            ],
            // Student Fee
            [
                'id' => 55,
                'display_name' => 'স্টুডেন্ট ফি দেখা',
                'name' => 'can-view-student-fee',
                'guard_name' => 'web',
                'group_name' => 'Student Fee Management',
                'is_active' => true,
            ],
            [
                'id' => 56,
                'display_name' => 'স্টুডেন্ট ফি তৈরী করা',
                'name' => 'can-create-student-fee',
                'guard_name' => 'web',
                'group_name' => 'Student Fee Management',
                'is_active' => true,
            ],
            [
                'id' => 57,
                'display_name' => 'স্টুডেন্ট ফি আপডেট করা',
                'name' => 'can-edit-student-fee',
                'guard_name' => 'web',
                'group_name' => 'Student Fee Management',
                'is_active' => true,
            ],
            [
                'id' => 58,
                'display_name' => 'স্টুডেন্ট ফি ডিলিট করা',
                'name' => 'can-delete-student-fee',
                'guard_name' => 'web',
                'group_name' => 'Student Fee Management',
                'is_active' => true,
            ],
            [
                'id' => 61,
                'display_name' => 'স্টুডেন্ট ফি অনুমোদন করা',
                'name' => 'can-approve-student-fee',
                'guard_name' => 'web',
                'group_name' => 'Student Fee Management',
                'is_active' => true,
            ],
            // Hall Attachment
            [
                'id' => 59,
                'display_name' => 'হল এটাচমেন্ট স্ট্যাটাস পরিবর্তন',
                'name' => 'can-change-status-hall-attachment',
                'guard_name' => 'web',
                'group_name' => 'Hall Attachment Management',
                'is_active' => true,
            ],
            // Dashboard
            [
                'id' => 60,
                'display_name' => 'ড্যাশবোর্ড দেখা',
                'name' => 'can-view-dashboard',
                'guard_name' => 'web',
                'group_name' => 'Dashboard',
                'is_active' => true,
            ],
            // Fee Configuration
            [
                'id' => 62,
                'display_name' => 'ফি কনফিগারেশন দেখা',
                'name' => 'can-view-fee-configuration',
                'guard_name' => 'web',
                'group_name' => 'Fee Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 63,
                'display_name' => 'ফি কনফিগারেশন তৈরী করা',
                'name' => 'can-create-fee-configuration',
                'guard_name' => 'web',
                'group_name' => 'Fee Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 64,
                'display_name' => 'ফি কনফিগারেশন আপডেট করা',
                'name' => 'can-edit-fee-configuration',
                'guard_name' => 'web',
                'group_name' => 'Fee Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 65,
                'display_name' => 'ফি কনফিগারেশন ডিলিট করা',
                'name' => 'can-delete-fee-configuration',
                'guard_name' => 'web',
                'group_name' => 'Fee Configuration Management',
                'is_active' => true,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::create($permission);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
